-- V74 Yemen-first expansion: family, household and everyday services.
-- Quote based: prices vary by locality, scope and provider.
INSERT OR IGNORE INTO categories(id, parent_id, slug, name_i18n, description_i18n, icon, keywords, module_type, sort_order, is_active, created_at, updated_at)
VALUES ('cat-family-life-yemen', NULL, 'family-life', '{"ar":"الأسرة والحياة اليومية","en":"Family & daily life"}', '{"ar":"خدمات يومية منزلية وشخصية مناسبة للأسر في المدن والريف","en":"Everyday household and personal services for families in urban and rural areas"}', '👨‍👩‍👧‍👦', '["اسرة","أسرة","بيت","ملابس","خياطة","طبخ","غسيل"]', 'STANDARD', 7, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO services(id, category_id, slug, name_i18n, description_i18n, icon, keywords, pricing_type, base_price, form_schema, cancellation_policy_id, default_priority, sort_order, is_active, created_at, updated_at)
VALUES
('svc-tailoring-yemen','cat-family-life-yemen','tailoring-alterations','{"ar":"خياطة وتعديل الملابس","en":"Tailoring & clothing alterations"}','{"ar":"تفصيل أو تعديل أو إصلاح الملابس مع إمكانية الاستلام والتوصيل","en":"Tailoring, alterations or clothing repair with optional pickup and delivery"}','🧵','["خياطة","خياط","تفصيل","تعديل ملابس","تضييق","توسيع","إصلاح ملابس"]','QUOTE',NULL,'[{"key":"request","type":"textarea","label":{"ar":"ما المطلوب؟","en":"What do you need?"},"required":true},{"key":"pickup_delivery","type":"boolean","label":{"ar":"هل تحتاج استلام وتسليم؟","en":"Need pickup and delivery?"},"required":false}]','default','NORMAL',1,1,datetime('now'),datetime('now')),
('svc-home-cooking-yemen','cat-family-life-yemen','home-cooking-catering','{"ar":"طبخ منزلي وتجهيز مناسبات","en":"Home cooking & catering"}','{"ar":"طلب طبخ منزلي أو تجهيز طعام لمناسبة أو أسرة حسب الاتفاق","en":"Home cooking or food preparation for a family or event by agreement"}','🍲','["طبخ","طبخ منزلي","مطبخ","طباخ","تجهيز مناسبة","وليمة","عزومة"]','QUOTE',NULL,'[{"key":"request","type":"textarea","label":{"ar":"ما المطلوب وعدد الأشخاص التقريبي؟","en":"What is needed and approximate number of people?"},"required":true},{"key":"date","type":"text","label":{"ar":"موعد الحاجة","en":"Needed date"},"required":false}]','default','NORMAL',2,1,datetime('now'),datetime('now')),
('svc-laundry-ironing-yemen','cat-family-life-yemen','laundry-ironing','{"ar":"غسيل وكي الملابس","en":"Laundry & ironing"}','{"ar":"غسيل أو كي الملابس مع إمكانية الاستلام والتسليم حسب مقدم الخدمة","en":"Laundry or ironing with optional pickup and delivery"}','👕','["غسيل ملابس","غسيل","كي","مكواة","ملابس"]','QUOTE',NULL,'[{"key":"quantity_note","type":"text","label":{"ar":"الكمية أو عدد القطع التقريبي","en":"Approximate quantity"},"required":false},{"key":"pickup_delivery","type":"boolean","label":{"ar":"هل تحتاج استلام وتسليم؟","en":"Need pickup and delivery?"},"required":false}]','default','NORMAL',3,1,datetime('now'),datetime('now')),
('svc-water-pump-maintenance-yemen','cat-family-life-yemen','water-pump-maintenance','{"ar":"صيانة مضخات المياه","en":"Water pump maintenance"}','{"ar":"فحص أو إصلاح أو تركيب مضخة مياه منزلية أو زراعية","en":"Inspect, repair or install a household or agricultural water pump"}','🔧','["مضخة ماء","مضخة مياه","موتور ماء","طرمبة ماء","مضخة خربانة","موتور الماء"]','QUOTE',NULL,'[{"key":"issue","type":"textarea","label":{"ar":"ما المشكلة أو المطلوب؟","en":"What is needed?"},"required":true}]','default','NORMAL',4,1,datetime('now'),datetime('now'));
